### ISSUE TITLE
[Refactor]: Color custom properties, global css file

### ISSUE THREAD

**Issue by james-c-lars** [cmwall0605/cse112-sp22-group8#62]
### Describe which part of the project code you are refactoring
The custom properties that define our colors, as well as any custom properties we use for font in the future

### What will be different about the refactored version?
There will be a separate global.css file which will contain all of our custom properties that each page will use

### What is being accomplished by refactoring?
This will prevent the code duplication at the top of each page redefining the color custom properties. It'll allow us to manage them in a single location.

Additionally, a global.js file might be needed at some point for stats tracking. Currently it's a little busted, but that's better for a separate issue. Having both a global.css and global.js file would thematically work together

**Comment by cmwall0605** [comment]
Forgot to mention that this issue was co-opted into the frenemies part of the project, where we included things like gradients and more color diversity to spruce up the website. For reference, the issue posted [the report](https://github.com/cmwall0605/cse112-sp22-group8/blob/main/admin/frenemies-interaction/frenemies-interaction-report.md) that this is referring to was "Get a more lively color palette".
